In [61]:
list(range(0,20,2))

TypeError: 'list' object is not callable

In [16]:
import numpy as np

list = [[1,2,3], [4,5,6],[7,8,9]]

d = np.array(list)
#print(d)

sum_all = [0]*3
for i in list:
    sum_all[i] += sum(d[:,i])

    

TypeError: list indices must be integers or slices, not list

In [17]:
np.array([1,2,3])

array([1, 2, 3])

In [31]:
#define a random seed first:
np.random.seed(12)
np.random.random(10)

array([0.15416284, 0.7400497 , 0.26331502, 0.53373939, 0.01457496,
       0.91874701, 0.90071485, 0.03342143, 0.95694934, 0.13720932])

In [33]:
list1 = [43,356,'hello', 90]
list2 = [str(x) for x in list1]
list2

['43', '356', 'hello', '90']

In [34]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [36]:
np.array([1,2,3]) + np.array([3,4,5])

array([4, 6, 8])

In [42]:
np.concatenate([np.array([1,2,3]), np.array([3,4,5])

SyntaxError: unexpected EOF while parsing (<ipython-input-42-e9a6afc702c2>, line 1)

In [43]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [47]:
print(np.full(8,12))

[12 12 12 12 12 12 12 12]


In [49]:
np.arange(3)

array([0, 1, 2])

In [50]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [58]:
np.arange(0,20,2).tolist()

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [59]:
np.random.normal(size=(3,3))

array([[ 0.75314283, -1.53472134,  0.00512708],
       [-0.12022767, -0.80698188,  2.87181939],
       [-0.59782292,  0.47245699,  1.09595612]])

In [60]:
np.random.random(size=(3,3))

array([[0.47122978, 0.8161683 , 0.28958678],
       [0.73312598, 0.70262236, 0.32756948],
       [0.33464753, 0.97805808, 0.62458211]])

In [62]:
np.random.exponential(size=(3,3))

array([[3.00202251, 1.45876033, 1.74302218],
       [0.52195449, 0.60021876, 0.51187889],
       [5.32633838, 0.19548482, 3.28600177]])

In [84]:
a=np.random.randint(0,10,(2,3))
a

array([[6, 5, 9],
       [2, 4, 0]])

In [70]:
a.shape

(4, 3)

In [71]:
type(a.shape)

tuple

In [74]:
a.shape[0]

4

In [76]:
a.size

12

In [77]:
a.ndim

2

In [78]:
a.dtype

dtype('int64')

In [79]:
a.nbytes

96

In [80]:
a

array([[5, 4, 0],
       [3, 7, 9],
       [6, 8, 6],
       [1, 4, 9]])

In [81]:
a[0,0]

5

In [82]:
a[:,-1]

array([0, 9, 6, 9])

In [85]:
a[1,:]

array([2, 4, 0])

In [94]:
a


array([[6, 5, 9],
       [2, 4, 0]])

In [96]:
a[:]

array([[6, 5, 9],
       [2, 4, 0]])

In [100]:
a[1:,:]#last row

array([[2, 4, 0]])

In [104]:
a[:1,:]#first row

array([[6, 5, 9]])

In [107]:
a[:,:1]#first col

array([[6],
       [2]])

In [114]:
a[:,0]#second col

array([6, 2])

In [113]:
a[:,-2]#second col

array([5, 4])

In [116]:
a[:,-1]#second col

array([9, 0])

In [125]:
#bigger array
a=np.random.randint(low=1, high=1000, size=(5,2,3))
a

array([[[427, 360, 808],
        [159, 506, 786]],

       [[583, 466, 452],
        [528, 385, 546]],

       [[685,  46, 377],
        [277, 795, 297]],

       [[585, 473, 777],
        [ 16,  77, 319]],

       [[944, 660, 234],
        [911, 159, 684]]])

In [136]:
a[3, :, :]

array([[585, 473, 777],
       [ 16,  77, 319]])

In [137]:
a[3] #same as above

array([[585, 473, 777],
       [ 16,  77, 319]])

In [138]:
a

array([[[427, 360, 808],
        [159, 506, 786]],

       [[583, 466, 452],
        [528, 385, 546]],

       [[685,  46, 377],
        [277, 795, 297]],

       [[585, 473, 777],
        [ 16,  77, 319]],

       [[944, 660, 234],
        [911, 159, 684]]])

In [140]:
b=np.random.randint(low=1, high=2000, size=(7,4,3))
b

array([[[1296,  911, 1286],
        [1090,  912, 1815],
        [ 756,   83, 1172],
        [1309,  146, 1242]],

       [[ 734, 1823,  532],
        [ 835, 1635,  176],
        [ 751, 1980,  649],
        [ 938,  116, 1190]],

       [[1722,  642,  568],
        [ 805, 1726, 1550],
        [ 465,  175, 1886],
        [ 233, 1908, 1234]],

       [[1701, 1547,  568],
        [1987, 1779, 1936],
        [ 831, 1375, 1573],
        [ 737,  985,  948]],

       [[ 646, 1635, 1856],
        [1536,  411, 1797],
        [  31,  408,  990],
        [1206,  545, 1692]],

       [[1987, 1613,  453],
        [1728, 1559,  999],
        [1438,  947,  216],
        [1971, 1654, 1954]],

       [[ 454, 1748, 1839],
        [ 376, 1966, 1756],
        [ 752, 1896, 1170],
        [1651, 1042,  214]]])

In [141]:
np.sum(ab)

NameError: name 'ab' is not defined

In [142]:
a


array([[[427, 360, 808],
        [159, 506, 786]],

       [[583, 466, 452],
        [528, 385, 546]],

       [[685,  46, 377],
        [277, 795, 297]],

       [[585, 473, 777],
        [ 16,  77, 319]],

       [[944, 660, 234],
        [911, 159, 684]]])

In [143]:
b

array([[[1296,  911, 1286],
        [1090,  912, 1815],
        [ 756,   83, 1172],
        [1309,  146, 1242]],

       [[ 734, 1823,  532],
        [ 835, 1635,  176],
        [ 751, 1980,  649],
        [ 938,  116, 1190]],

       [[1722,  642,  568],
        [ 805, 1726, 1550],
        [ 465,  175, 1886],
        [ 233, 1908, 1234]],

       [[1701, 1547,  568],
        [1987, 1779, 1936],
        [ 831, 1375, 1573],
        [ 737,  985,  948]],

       [[ 646, 1635, 1856],
        [1536,  411, 1797],
        [  31,  408,  990],
        [1206,  545, 1692]],

       [[1987, 1613,  453],
        [1728, 1559,  999],
        [1438,  947,  216],
        [1971, 1654, 1954]],

       [[ 454, 1748, 1839],
        [ 376, 1966, 1756],
        [ 752, 1896, 1170],
        [1651, 1042,  214]]])

In [146]:
np.multiply(a,b)

ValueError: operands could not be broadcast together with shapes (5,2,3) (7,4,3) 

In [155]:
a = np.array([1,4,9], [5,3,5])
b = np.array([2,3,4], [5,6,7])

TypeError: Field elements must be 2- or 3-tuples, got '5'

In [156]:
np.random.seed(123)
rand = np.random.random(10)
rand

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752])

In [157]:
np.sqrt(rand)

array([0.83454729, 0.53491993, 0.47628925, 0.74250574, 0.84821517,
       0.65046634, 0.9903354 , 0.8275444 , 0.69349254, 0.62619288])

In [158]:
my_mean = np.mean(rand)
my_mean

0.544199352975335

In [160]:
rand - my_mean

array([ 0.15226983, -0.25806002, -0.3173479 ,  0.00711542,  0.17526962,
       -0.12109289,  0.43656485,  0.14063039, -0.06326745, -0.15208183])

In [161]:
(rand - my_mean)**2

array([2.31861019e-02, 6.65949729e-02, 1.00709689e-01, 5.06291464e-05,
       3.07194386e-02, 1.46634887e-02, 1.90588864e-01, 1.97769054e-02,
       4.00277042e-03, 2.31288845e-02])

In [162]:
np.power(rand-my_mean,2)

array([2.31861019e-02, 6.65949729e-02, 1.00709689e-01, 5.06291464e-05,
       3.07194386e-02, 1.46634887e-02, 1.90588864e-01, 1.97769054e-02,
       4.00277042e-03, 2.31288845e-02])

In [163]:
np.mean(np.power(rand-my_mean,2))

0.04734217450052595

In [164]:
np.sqrt(np.mean(np.power(rand-my_mean,2)))

0.21758256938579879

In [166]:
np.std(rand)

0.21758256938579879

In [167]:
from time import time

n = 10000000 #10m


In [168]:
start_time = time()

list_of_numbers = []
for i in range(n):
    list_of_numbers.append(i**5)
    
end_time = time()
end_time - start_time

print(end_time - start_time)

    


NameError: name 'n' is not defined

In [170]:
#splitting arrays:

#hundred = np.array(range(1,101))
hundred = np.arange(1,101)
hundred

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [172]:
import pandas as pd
pd.__version__

'1.2.4'